// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$150 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$150() {}
    static final VarHandle const$0 = constants$147.const$5.varHandle(PathElement.groupElement("check_tensors"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("n_ctx"),
        JAVA_INT.withName("n_batch"),
        JAVA_INT.withName("n_ubatch"),
        JAVA_INT.withName("n_seq_max"),
        JAVA_INT.withName("n_threads"),
        JAVA_INT.withName("n_threads_batch"),
        JAVA_INT.withName("rope_scaling_type"),
        JAVA_INT.withName("pooling_type"),
        JAVA_INT.withName("attention_type"),
        JAVA_FLOAT.withName("rope_freq_base"),
        JAVA_FLOAT.withName("rope_freq_scale"),
        JAVA_FLOAT.withName("yarn_ext_factor"),
        JAVA_FLOAT.withName("yarn_attn_factor"),
        JAVA_FLOAT.withName("yarn_beta_fast"),
        JAVA_FLOAT.withName("yarn_beta_slow"),
        JAVA_INT.withName("yarn_orig_ctx"),
        JAVA_FLOAT.withName("defrag_thold"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("cb_eval"),
        RuntimeHelper.POINTER.withName("cb_eval_user_data"),
        JAVA_INT.withName("type_k"),
        JAVA_INT.withName("type_v"),
        JAVA_BOOLEAN.withName("logits_all"),
        JAVA_BOOLEAN.withName("embeddings"),
        JAVA_BOOLEAN.withName("offload_kqv"),
        JAVA_BOOLEAN.withName("flash_attn"),
        JAVA_BOOLEAN.withName("no_perf"),
        MemoryLayout.paddingLayout(3),
        RuntimeHelper.POINTER.withName("abort_callback"),
        RuntimeHelper.POINTER.withName("abort_callback_data")
    ).withName("llama_context_params");
    static final VarHandle const$2 = constants$150.const$1.varHandle(PathElement.groupElement("n_ctx"));
    static final VarHandle const$3 = constants$150.const$1.varHandle(PathElement.groupElement("n_batch"));
    static final VarHandle const$4 = constants$150.const$1.varHandle(PathElement.groupElement("n_ubatch"));
    static final VarHandle const$5 = constants$150.const$1.varHandle(PathElement.groupElement("n_seq_max"));
}


