// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$173 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$173() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_rm_adapter_lora",
        constants$12.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_clear_adapter_lora",
        constants$0.const$3
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_apply_adapter_cvec",
        constants$173.const$2
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("pos")
    ).withName("llama_kv_cache_view_cell");
    static final VarHandle const$5 = constants$173.const$4.varHandle(MemoryLayout.PathElement.groupElement("pos"));
}


