// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$145 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$145() {}
    static final VarHandle const$0 = constants$144.const$2.varHandle(PathElement.groupElement("sorted"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_BOOLEAN,
        JAVA_FLOAT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(llama_progress_callback.class, "apply", constants$145.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$145.const$1
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("n_tokens"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("token"),
        RuntimeHelper.POINTER.withName("embd"),
        RuntimeHelper.POINTER.withName("pos"),
        RuntimeHelper.POINTER.withName("n_seq_id"),
        RuntimeHelper.POINTER.withName("seq_id"),
        RuntimeHelper.POINTER.withName("logits")
    ).withName("llama_batch");
    static final VarHandle const$5 = constants$145.const$4.varHandle(PathElement.groupElement("n_tokens"));
}


