// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$62 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$62() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_group_norm_inplace",
        constants$61.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_l2_norm",
        constants$61.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_l2_norm_inplace",
        constants$61.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_FLOAT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_rms_norm_back",
        constants$62.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_mul_mat",
        constants$14.const$0
    );
}


