// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_is_contiguous_2",
        constants$35.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_are_same_shape",
        constants$36.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_are_same_stride",
        constants$36.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_can_repeat",
        constants$36.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_tensor_overhead",
        constants$36.const$5
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_BOOLEAN,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "ggml_validate_row_data",
        constants$43.const$5
    );
}


