// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$122 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$122() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_device_register",
        constants$0.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_reg_count",
        constants$36.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_reg_get",
        constants$122.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_backend_reg_by_name",
        constants$16.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_count",
        constants$36.const$5
    );
}


