// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$170 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$170() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_model_meta_count",
        constants$5.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_model_meta_key_by_index",
        constants$170.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_model_meta_val_str_by_index",
        constants$170.const$1
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_model_desc",
        constants$170.const$4
    );
}


