// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$176 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$176() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_copy_state_data",
        constants$105.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_state_set_data",
        constants$175.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_set_state_data",
        constants$105.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_state_load_file",
        constants$176.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_load_session_file",
        constants$176.const$3
    );
}


