// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$49 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$49() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_get_data",
        constants$16.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_get_data_f32",
        constants$16.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_get_name",
        constants$16.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_set_name",
        constants$12.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandleVariadic(
        "ggml_format_name",
        constants$12.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_set_input",
        constants$0.const$3
    );
}


