// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$200 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$200() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_split_prefix",
        constants$199.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_print_system_info",
        constants$18.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(llama_log_set$log_callback.class, "apply", constants$81.const$5);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_log_set",
        constants$17.const$5
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_DOUBLE.withName("t_start_ms"),
        JAVA_DOUBLE.withName("t_load_ms"),
        JAVA_DOUBLE.withName("t_p_eval_ms"),
        JAVA_DOUBLE.withName("t_eval_ms"),
        JAVA_INT.withName("n_p_eval"),
        JAVA_INT.withName("n_eval")
    ).withName("llama_perf_context_data");
    static final VarHandle const$5 = constants$200.const$4.varHandle(PathElement.groupElement("t_start_ms"));
}


