// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$199 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$199() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_sampler_apply",
        constants$17.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_sampler_reset",
        constants$0.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_sampler_clone",
        constants$16.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_sampler_free",
        constants$0.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_BOOLEAN.withName("no_perf")
        ).withName("llama_sampler_chain_params")
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_sampler_chain_init",
        constants$199.const$4
    );
}


