// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$147 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$147() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("tag"),
        MemoryLayout.sequenceLayout(128, JAVA_BYTE).withName("key"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.unionLayout(
            JAVA_LONG.withName("val_i64"),
            JAVA_DOUBLE.withName("val_f64"),
            JAVA_BOOLEAN.withName("val_bool"),
            MemoryLayout.sequenceLayout(128, JAVA_BYTE).withName("val_str")
        ).withName("$anon$0")
    ).withName("llama_model_kv_override");
    static final VarHandle const$1 = constants$147.const$0.varHandle(PathElement.groupElement("tag"));
    static final VarHandle const$2 = constants$147.const$0.varHandle(PathElement.groupElement("$anon$0"), PathElement.groupElement("val_i64"));
    static final VarHandle const$3 = constants$147.const$0.varHandle(PathElement.groupElement("$anon$0"), PathElement.groupElement("val_f64"));
    static final VarHandle const$4 = constants$147.const$0.varHandle(PathElement.groupElement("$anon$0"), PathElement.groupElement("val_bool"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("devices"),
        JAVA_INT.withName("n_gpu_layers"),
        JAVA_INT.withName("split_mode"),
        JAVA_INT.withName("main_gpu"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("tensor_split"),
        RuntimeHelper.POINTER.withName("progress_callback"),
        RuntimeHelper.POINTER.withName("progress_callback_user_data"),
        RuntimeHelper.POINTER.withName("kv_overrides"),
        JAVA_BOOLEAN.withName("vocab_only"),
        JAVA_BOOLEAN.withName("use_mmap"),
        JAVA_BOOLEAN.withName("use_mlock"),
        JAVA_BOOLEAN.withName("check_tensors"),
        MemoryLayout.paddingLayout(4)
    ).withName("llama_model_params");
}


