// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$195 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$195() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_sampler_chain_remove",
        constants$93.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_greedy",
        constants$18.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_dist",
        constants$30.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_softmax",
        constants$18.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_top_k",
        constants$30.const$4
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_FLOAT,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_top_p",
        constants$195.const$5
    );
}


