// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$132 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$132() {}
    static final VarHandle const$0 = constants$131.const$2.varHandle(MemoryLayout.PathElement.groupElement("threadpool"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(ggml_cplan.abort_callback.class, "apply", constants$35.const$4);
    static final VarHandle const$2 = constants$131.const$2.varHandle(MemoryLayout.PathElement.groupElement("abort_callback"));
    static final VarHandle const$3 = constants$131.const$2.varHandle(MemoryLayout.PathElement.groupElement("abort_callback_data"));
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_numa_init",
        constants$98.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_BOOLEAN);
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "ggml_is_numa",
        constants$132.const$5
    );
}


