// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$169 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$169() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_model_is_recurrent",
        constants$35.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_model_quantize",
        constants$19.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_adapter_lora_init",
        constants$12.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_adapter_lora_free",
        constants$0.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_FLOAT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_set_adapter_lora",
        constants$169.const$4
    );
}


