// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$156 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$156() {}
    static final VarHandle const$0 = constants$155.const$2.varHandle(PathElement.groupElement("token_embedding_type"));
    static final VarHandle const$1 = constants$155.const$2.varHandle(PathElement.groupElement("allow_requantize"));
    static final VarHandle const$2 = constants$155.const$2.varHandle(PathElement.groupElement("quantize_output_tensor"));
    static final VarHandle const$3 = constants$155.const$2.varHandle(PathElement.groupElement("only_copy"));
    static final VarHandle const$4 = constants$155.const$2.varHandle(PathElement.groupElement("pure"));
    static final VarHandle const$5 = constants$155.const$2.varHandle(PathElement.groupElement("keep_split"));
}


