// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$116 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$116() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_description",
        constants$16.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_memory",
        constants$83.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_type",
        constants$5.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_get_props",
        constants$17.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_backend_reg",
        constants$16.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_init",
        constants$12.const$5
    );
}


