// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$128 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$128() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_set_eval_callback",
        constants$84.const$2
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buffer"),
        RuntimeHelper.POINTER.withName("ctx_allocated"),
        RuntimeHelper.POINTER.withName("ctx_unallocated"),
        RuntimeHelper.POINTER.withName("graph")
    ).withName("ggml_backend_graph_copy");
    static final VarHandle const$2 = constants$128.const$1.varHandle(MemoryLayout.PathElement.groupElement("buffer"));
    static final VarHandle const$3 = constants$128.const$1.varHandle(MemoryLayout.PathElement.groupElement("ctx_allocated"));
    static final VarHandle const$4 = constants$128.const$1.varHandle(MemoryLayout.PathElement.groupElement("ctx_unallocated"));
    static final VarHandle const$5 = constants$128.const$1.varHandle(MemoryLayout.PathElement.groupElement("graph"));
}


