// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$58 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$58() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_elu_inplace",
        constants$12.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_relu",
        constants$12.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_FLOAT,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_leaky_relu",
        constants$58.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_relu_inplace",
        constants$12.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_sigmoid",
        constants$12.const$5
    );
}


