// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$130 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$130() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$129.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(ggml_backend_compare_graph_backend$callback.class, "apply", constants$129.const$4);
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_compare_graph_backend",
        constants$130.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_backend_tensor_alloc",
        constants$19.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_backend_view_init",
        constants$5.const$4
    );
}


