// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$158 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$158() {}
    static final VarHandle const$0 = constants$157.const$5.varHandle(PathElement.groupElement("no_perf"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("role"),
        RuntimeHelper.POINTER.withName("content")
    ).withName("llama_chat_message");
    static final VarHandle const$2 = constants$158.const$1.varHandle(PathElement.groupElement("role"));
    static final VarHandle const$3 = constants$158.const$1.varHandle(PathElement.groupElement("content"));
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("devices"),
        JAVA_INT.withName("n_gpu_layers"),
        JAVA_INT.withName("split_mode"),
        JAVA_INT.withName("main_gpu"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("tensor_split"),
        RuntimeHelper.POINTER.withName("progress_callback"),
        RuntimeHelper.POINTER.withName("progress_callback_user_data"),
        RuntimeHelper.POINTER.withName("kv_overrides"),
        JAVA_BOOLEAN.withName("vocab_only"),
        JAVA_BOOLEAN.withName("use_mmap"),
        JAVA_BOOLEAN.withName("use_mlock"),
        JAVA_BOOLEAN.withName("check_tensors"),
        MemoryLayout.paddingLayout(4)
    ).withName("llama_model_params"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_model_default_params",
        constants$158.const$4
    );
}


