// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$42 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$42() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_is_matrix",
        constants$35.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_is_3d",
        constants$35.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_n_dims",
        constants$5.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_is_contiguous",
        constants$35.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_is_contiguous_0",
        constants$35.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_is_contiguous_1",
        constants$35.const$4
    );
}


