// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$67 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$67() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_reshape",
        constants$14.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_reshape_1d",
        constants$65.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_reshape_2d",
        constants$66.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_reshape_3d",
        constants$66.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_reshape_4d",
        constants$66.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_view_1d",
        constants$66.const$0
    );
}


