// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$182 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$182() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_get_embeddings_ith",
        constants$93.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_get_embeddings_seq",
        constants$93.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_vocab_get_text",
        constants$93.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_vocab_get_score",
        constants$133.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_vocab_get_attr",
        constants$132.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "llama_vocab_is_eog",
        constants$182.const$5
    );
}


