// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$193 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$193() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_add_eos_token",
        constants$35.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_token_fim_pre",
        constants$5.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_token_fim_suf",
        constants$5.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_token_fim_mid",
        constants$5.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_token_fim_pad",
        constants$5.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_token_fim_rep",
        constants$5.const$4
    );
}


