// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$121 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$121() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$16.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(ggml_backend_set_abort_callback_t.class, "apply", constants$84.const$2);
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("name"),
        RuntimeHelper.POINTER.withName("value")
    ).withName("ggml_backend_feature");
    static final VarHandle const$3 = constants$121.const$2.varHandle(MemoryLayout.PathElement.groupElement("name"));
    static final VarHandle const$4 = constants$121.const$2.varHandle(MemoryLayout.PathElement.groupElement("value"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(ggml_backend_get_features_t.class, "apply", constants$16.const$0);
}


