// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$191 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$191() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_token_get_score",
        constants$135.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_token_get_attr",
        constants$133.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_token_is_eog",
        constants$188.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_token_is_control",
        constants$188.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_token_bos",
        constants$5.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_token_eos",
        constants$5.const$4
    );
}


