// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$119 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$119() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(ggml_backend_set_n_threads_t.class, "apply", constants$62.const$4);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$62.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(ggml_backend_dev_get_extra_bufts_t.class, "apply", constants$16.const$0);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$16.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(ggml_backend_set_abort_callback_t.class, "apply", constants$83.const$1);
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("name"),
        RuntimeHelper.POINTER.withName("value")
    ).withName("ggml_backend_feature");
}


