// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$200 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$200() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_sampler_chain_add",
        constants$17.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_sampler_chain_get",
        constants$95.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_sampler_chain_n",
        constants$5.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_sampler_chain_remove",
        constants$95.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_greedy",
        constants$18.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_dist",
        constants$30.const$4
    );
}


