// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$140 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$140() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_cpu_has_vxe",
        constants$15.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_cpu_has_wasm_simd",
        constants$15.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_cpu_has_llamafile",
        constants$15.const$4
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(ggml_vec_dot_t.class, "apply", constants$140.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$140.const$3
    );
}


