// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$89 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$89() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(ggml_map_custom1$fun.class, "apply", constants$87.const$3);
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_map_custom1",
        constants$89.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(ggml_map_custom1_inplace$fun.class, "apply", constants$87.const$3);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_map_custom1_inplace",
        constants$89.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(ggml_map_custom2$fun.class, "apply", constants$88.const$0);
}


