// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$129 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$129() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buffer"),
        RuntimeHelper.POINTER.withName("ctx_allocated"),
        RuntimeHelper.POINTER.withName("ctx_unallocated"),
        RuntimeHelper.POINTER.withName("graph")
    ).withName("ggml_backend_graph_copy"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_graph_copy",
        constants$129.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("buffer"),
            RuntimeHelper.POINTER.withName("ctx_allocated"),
            RuntimeHelper.POINTER.withName("ctx_unallocated"),
            RuntimeHelper.POINTER.withName("graph")
        ).withName("ggml_backend_graph_copy")
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_graph_copy_free",
        constants$129.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_BOOLEAN,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(ggml_backend_eval_callback.class, "apply", constants$129.const$4);
}


