// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$124 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$124() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_reserve",
        constants$36.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_get_n_backends",
        constants$5.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_get_backend",
        constants$93.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_get_n_splits",
        constants$5.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_get_n_copies",
        constants$5.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_get_buffer_size",
        constants$105.const$3
    );
}


