// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$128 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$128() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_BOOLEAN,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(ggml_backend_eval_callback.class, "apply", constants$128.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$128.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(ggml_backend_compare_graph_backend$callback.class, "apply", constants$128.const$0);
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_backend_compare_graph_backend",
        constants$128.const$4
    );
}


