// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$103 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$103() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_gallocr_new",
        constants$16.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_gallocr_new_n",
        constants$93.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_gallocr_free",
        constants$0.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_gallocr_reserve",
        constants$36.const$1
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_gallocr_reserve_n",
        constants$103.const$4
    );
}


