// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$117 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$117() {}
    static final VarHandle const$0 = constants$116.const$2.varHandle(MemoryLayout.PathElement.groupElement("memory_total"));
    static final VarHandle const$1 = constants$116.const$2.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_name",
        constants$16.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_description",
        constants$16.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_memory",
        constants$84.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_type",
        constants$5.const$4
    );
}


