// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$179 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$179() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_rm",
        constants$177.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_cp",
        constants$177.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_keep",
        constants$63.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_add",
        constants$177.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_div",
        constants$177.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_pos_max",
        constants$133.const$5
    );
}


