// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$100 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$100() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(512, JAVA_BOOLEAN).withName("cpumask"),
        JAVA_INT.withName("n_threads"),
        JAVA_INT.withName("prio"),
        JAVA_INT.withName("poll"),
        JAVA_BOOLEAN.withName("strict_cpu"),
        JAVA_BOOLEAN.withName("paused"),
        MemoryLayout.paddingLayout(2)
    ).withName("ggml_threadpool_params");
    static final VarHandle const$1 = constants$100.const$0.varHandle(PathElement.groupElement("n_threads"));
    static final VarHandle const$2 = constants$100.const$0.varHandle(PathElement.groupElement("prio"));
    static final VarHandle const$3 = constants$100.const$0.varHandle(PathElement.groupElement("poll"));
    static final VarHandle const$4 = constants$100.const$0.varHandle(PathElement.groupElement("strict_cpu"));
    static final VarHandle const$5 = constants$100.const$0.varHandle(PathElement.groupElement("paused"));
}


