// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$183 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$183() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_state_seq_set_data",
        constants$182.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_state_seq_save_file",
        constants$183.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_state_seq_load_file",
        constants$183.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("n_tokens"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("token"),
        RuntimeHelper.POINTER.withName("embd"),
        RuntimeHelper.POINTER.withName("pos"),
        RuntimeHelper.POINTER.withName("n_seq_id"),
        RuntimeHelper.POINTER.withName("seq_id"),
        RuntimeHelper.POINTER.withName("logits")
    ).withName("llama_batch"),
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "llama_batch_get_one",
        constants$183.const$5
    );
}


