// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$95 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$95() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_graph_size",
        constants$5.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_graph_node",
        constants$95.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_graph_nodes",
        constants$16.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_graph_n_nodes",
        constants$5.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_graph_add_node",
        constants$17.const$5
    );
}


