// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$97 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$97() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_graph_export",
        constants$17.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_graph_import",
        constants$14.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_graph_print",
        constants$0.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_graph_dump_dot",
        constants$84.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(ggml_log_callback.class, "apply", constants$83.const$0);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(ggml_log_set$log_callback.class, "apply", constants$83.const$0);
}


