// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$92 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$92() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_map_custom3",
        constants$92.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(ggml_map_custom3_inplace$fun.class, "apply", constants$89.const$4);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_map_custom3_inplace",
        constants$92.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_cross_entropy_loss",
        constants$14.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_cross_entropy_loss_back",
        constants$63.const$2
    );
}


