// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$86 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$86() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_map_custom1_inplace_f32",
        constants$14.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(ggml_map_custom2_f32$fun.class, "apply", constants$83.const$1);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_map_custom2_f32",
        constants$63.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(ggml_map_custom2_inplace_f32$fun.class, "apply", constants$83.const$1);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_map_custom2_inplace_f32",
        constants$63.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(ggml_map_custom3_f32$fun.class, "apply", constants$83.const$4);
}


