// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$112 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$112() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_graph_compute",
        constants$12.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_graph_compute_async",
        constants$12.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_backend_supports_op",
        constants$36.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_supports_buft",
        constants$36.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_backend_offload_op",
        constants$36.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_backend_tensor_copy_async",
        constants$83.const$4
    );
}


