// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$178 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$178() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_kv_self_seq_div",
        constants$177.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_kv_self_seq_pos_max",
        constants$133.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_kv_self_defrag",
        constants$0.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_kv_self_can_shift",
        constants$35.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_kv_self_update",
        constants$0.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_clear",
        constants$0.const$3
    );
}


