// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$143 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$143() {}
    static final VarHandle const$0 = constants$142.const$4.varHandle(MemoryLayout.PathElement.groupElement("from_float"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(ggml_type_traits_cpu.vec_dot.class, "apply", constants$142.const$1);
    static final VarHandle const$2 = constants$142.const$4.varHandle(MemoryLayout.PathElement.groupElement("vec_dot"));
    static final VarHandle const$3 = constants$142.const$4.varHandle(MemoryLayout.PathElement.groupElement("vec_dot_type"));
    static final VarHandle const$4 = constants$142.const$4.varHandle(MemoryLayout.PathElement.groupElement("nrows"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_get_type_traits_cpu",
        constants$30.const$4
    );
}


