// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$102 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$102() {}
    static final VarHandle const$0 = constants$101.const$4.varHandle(PathElement.groupElement("base"));
    static final VarHandle const$1 = constants$101.const$4.varHandle(PathElement.groupElement("alignment"));
    static final VarHandle const$2 = constants$101.const$4.varHandle(PathElement.groupElement("offset"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buffer"),
        RuntimeHelper.POINTER.withName("base"),
        JAVA_LONG.withName("alignment"),
        JAVA_LONG.withName("offset")
    ).withName("ggml_tallocr"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_tallocr_new",
        constants$102.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_tallocr_alloc",
        constants$17.const$5
    );
}


