// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$143 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$143() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_cpu_set_threadpool",
        constants$17.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(ggml_backend_cpu_set_abort_callback$abort_callback.class, "apply", constants$35.const$4);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_backend_cpu_set_abort_callback",
        constants$83.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_cpu_reg",
        constants$18.const$4
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("id"),
        JAVA_FLOAT.withName("logit"),
        JAVA_FLOAT.withName("p")
    ).withName("llama_token_data");
    static final VarHandle const$5 = constants$143.const$4.varHandle(PathElement.groupElement("id"));
}


