// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$201 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$201() {}
    static final VarHandle const$0 = constants$200.const$4.varHandle(PathElement.groupElement("t_load_ms"));
    static final VarHandle const$1 = constants$200.const$4.varHandle(PathElement.groupElement("t_p_eval_ms"));
    static final VarHandle const$2 = constants$200.const$4.varHandle(PathElement.groupElement("t_eval_ms"));
    static final VarHandle const$3 = constants$200.const$4.varHandle(PathElement.groupElement("n_p_eval"));
    static final VarHandle const$4 = constants$200.const$4.varHandle(PathElement.groupElement("n_eval"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_DOUBLE.withName("t_sample_ms"),
        JAVA_INT.withName("n_sample"),
        MemoryLayout.paddingLayout(4)
    ).withName("llama_perf_sampler_data");
}


