// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$183 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$183() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_vocab_is_control",
        constants$182.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_vocab_bos",
        constants$5.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_vocab_eos",
        constants$5.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_vocab_eot",
        constants$5.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_vocab_sep",
        constants$5.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_vocab_nl",
        constants$5.const$4
    );
}


