// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$123 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$123() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_get",
        constants$122.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_by_name",
        constants$16.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_by_type",
        constants$30.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_init_by_name",
        constants$12.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_backend_init_by_type",
        constants$20.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_backend_init_best",
        constants$18.const$4
    );
}


