// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$153 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$153() {}
    static final VarHandle const$0 = constants$152.const$3.varHandle(MemoryLayout.PathElement.groupElement("n_ubatch"));
    static final VarHandle const$1 = constants$152.const$3.varHandle(MemoryLayout.PathElement.groupElement("n_seq_max"));
    static final VarHandle const$2 = constants$152.const$3.varHandle(MemoryLayout.PathElement.groupElement("n_threads"));
    static final VarHandle const$3 = constants$152.const$3.varHandle(MemoryLayout.PathElement.groupElement("n_threads_batch"));
    static final VarHandle const$4 = constants$152.const$3.varHandle(MemoryLayout.PathElement.groupElement("rope_scaling_type"));
    static final VarHandle const$5 = constants$152.const$3.varHandle(MemoryLayout.PathElement.groupElement("pooling_type"));
}


