// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$100 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$100() {}
    static final VarHandle const$0 = constants$99.const$5.varHandle(MemoryLayout.PathElement.groupElement("type_name"));
    static final VarHandle const$1 = constants$99.const$5.varHandle(MemoryLayout.PathElement.groupElement("blck_size"));
    static final VarHandle const$2 = constants$99.const$5.varHandle(MemoryLayout.PathElement.groupElement("blck_size_interleave"));
    static final VarHandle const$3 = constants$99.const$5.varHandle(MemoryLayout.PathElement.groupElement("type_size"));
    static final VarHandle const$4 = constants$99.const$5.varHandle(MemoryLayout.PathElement.groupElement("is_quantized"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(ggml_type_traits.to_float.class, "apply", constants$31.const$4);
}


