// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * int (*funopen$x0)(void*,char*,int);
 * }
 */
public interface funopen$x0 {

    int apply(MemorySegment _x0, MemorySegment _x1, int _x2);
    static MemorySegment allocate(funopen$x0 fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$28.const$0, fi, constants$5.const$0, scope);
    }
    static funopen$x0 ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (MemorySegment __x0, MemorySegment __x1, int __x2) -> {
            try {
                return (int)constants$8.const$3.invokeExact(symbol, __x0, __x1, __x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


