// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * void (*ggml_custom1_op_t)(struct ggml_tensor* dst,struct ggml_tensor* a,int ith,int nth,void* userdata);
 * }
 */
public interface ggml_custom1_op_t {

    void apply(MemorySegment dst, MemorySegment a, int ith, int nth, MemorySegment userdata);
    static MemorySegment allocate(ggml_custom1_op_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$87.const$4, fi, constants$87.const$3, scope);
    }
    static ggml_custom1_op_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (MemorySegment _dst, MemorySegment _a, int _ith, int _nth, MemorySegment _userdata) -> {
            try {
                constants$87.const$5.invokeExact(symbol, _dst, _a, _ith, _nth, _userdata);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


