// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * void (*ggml_map_custom3_inplace_f32$fun)(struct ggml_tensor*,struct ggml_tensor*,struct ggml_tensor*,struct ggml_tensor*);
 * }
 */
public interface ggml_map_custom3_inplace_f32$fun {

    void apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, java.lang.foreign.MemorySegment _x2, java.lang.foreign.MemorySegment _x3);
    static MemorySegment allocate(ggml_map_custom3_inplace_f32$fun fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$88.const$2, fi, constants$84.const$5, scope);
    }
    static ggml_map_custom3_inplace_f32$fun ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, java.lang.foreign.MemorySegment __x2, java.lang.foreign.MemorySegment __x3) -> {
            try {
                constants$85.const$1.invokeExact(symbol, __x0, __x1, __x2, __x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


