// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * void (*ggml_backend_set_abort_callback_t)(struct ggml_backend* backend,_Bool (*abort_callback)(void*),void* abort_callback_data);
 * }
 */
public interface ggml_backend_set_abort_callback_t {

    void apply(java.lang.foreign.MemorySegment backend, java.lang.foreign.MemorySegment abort_callback, java.lang.foreign.MemorySegment abort_callback_data);
    static MemorySegment allocate(ggml_backend_set_abort_callback_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$121.const$1, fi, constants$84.const$2, scope);
    }
    static ggml_backend_set_abort_callback_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _backend, java.lang.foreign.MemorySegment _abort_callback, java.lang.foreign.MemorySegment _abort_callback_data) -> {
            try {
                constants$84.const$4.invokeExact(symbol, _backend, _abort_callback, _abort_callback_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


