// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * void (*ggml_from_float_t)(float* x,void* y,long long k);
 * }
 */
public interface ggml_from_float_t {

    void apply(MemorySegment x, MemorySegment y, long k);
    static MemorySegment allocate(ggml_from_float_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$98.const$0, fi, constants$31.const$4, scope);
    }
    static ggml_from_float_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (MemorySegment _x, MemorySegment _y, long _k) -> {
            try {
                constants$97.const$5.invokeExact(symbol, _x, _y, _k);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


