// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * _Bool (*ggml_backend_compare_graph_backend$callback)(int,struct ggml_tensor*,struct ggml_tensor*,void*);
 * }
 */
public interface ggml_backend_compare_graph_backend$callback {

    boolean apply(int node_index, MemorySegment t1, MemorySegment t2, MemorySegment user_data);
    static MemorySegment allocate(ggml_backend_compare_graph_backend$callback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$128.const$3, fi, constants$128.const$0, scope);
    }
    static ggml_backend_compare_graph_backend$callback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int _node_index, MemorySegment _t1, MemorySegment _t2, MemorySegment _user_data) -> {
            try {
                return (boolean)constants$128.const$2.invokeExact(symbol, _node_index, _t1, _t2, _user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


