// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct ggml_tallocr {
 *     struct ggml_backend_buffer* buffer;
 *     void* base;
 *     unsigned long alignment;
 *     unsigned long offset;
 * };
 * }
 */
public class ggml_tallocr {

    public static MemoryLayout $LAYOUT() {
        return constants$103.const$2;
    }
    public static VarHandle buffer$VH() {
        return constants$103.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct ggml_backend_buffer* buffer;
     * }
     */
    public static MemorySegment buffer$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$103.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct ggml_backend_buffer* buffer;
     * }
     */
    public static void buffer$set(MemorySegment seg, MemorySegment x) {
        constants$103.const$3.set(seg, x);
    }
    public static MemorySegment buffer$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$103.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void buffer$set(MemorySegment seg, long index, MemorySegment x) {
        constants$103.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle base$VH() {
        return constants$103.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * void* base;
     * }
     */
    public static MemorySegment base$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$103.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * void* base;
     * }
     */
    public static void base$set(MemorySegment seg, MemorySegment x) {
        constants$103.const$4.set(seg, x);
    }
    public static MemorySegment base$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$103.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void base$set(MemorySegment seg, long index, MemorySegment x) {
        constants$103.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle alignment$VH() {
        return constants$103.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long alignment;
     * }
     */
    public static long alignment$get(MemorySegment seg) {
        return (long)constants$103.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long alignment;
     * }
     */
    public static void alignment$set(MemorySegment seg, long x) {
        constants$103.const$5.set(seg, x);
    }
    public static long alignment$get(MemorySegment seg, long index) {
        return (long)constants$103.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void alignment$set(MemorySegment seg, long index, long x) {
        constants$103.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle offset$VH() {
        return constants$104.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long offset;
     * }
     */
    public static long offset$get(MemorySegment seg) {
        return (long)constants$104.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long offset;
     * }
     */
    public static void offset$set(MemorySegment seg, long x) {
        constants$104.const$0.set(seg, x);
    }
    public static long offset$get(MemorySegment seg, long index) {
        return (long)constants$104.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void offset$set(MemorySegment seg, long index, long x) {
        constants$104.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


