// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct ggml_type_traits {
 *     char* type_name;
 *     long long blck_size;
 *     long long blck_size_interleave;
 *     unsigned long type_size;
 *     _Bool is_quantized;
 *     void (*to_float)(void*,float*,long long);
 *     void (*from_float_ref)(float*,void*,long long);
 * };
 * }
 */
public class ggml_type_traits {

    public static MemoryLayout $LAYOUT() {
        return constants$98.const$1;
    }
    public static VarHandle type_name$VH() {
        return constants$98.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * char* type_name;
     * }
     */
    public static MemorySegment type_name$get(MemorySegment seg) {
        return (MemorySegment)constants$98.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * char* type_name;
     * }
     */
    public static void type_name$set(MemorySegment seg, MemorySegment x) {
        constants$98.const$2.set(seg, x);
    }
    public static MemorySegment type_name$get(MemorySegment seg, long index) {
        return (MemorySegment)constants$98.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void type_name$set(MemorySegment seg, long index, MemorySegment x) {
        constants$98.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle blck_size$VH() {
        return constants$98.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * long long blck_size;
     * }
     */
    public static long blck_size$get(MemorySegment seg) {
        return (long)constants$98.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * long long blck_size;
     * }
     */
    public static void blck_size$set(MemorySegment seg, long x) {
        constants$98.const$3.set(seg, x);
    }
    public static long blck_size$get(MemorySegment seg, long index) {
        return (long)constants$98.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void blck_size$set(MemorySegment seg, long index, long x) {
        constants$98.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle blck_size_interleave$VH() {
        return constants$98.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * long long blck_size_interleave;
     * }
     */
    public static long blck_size_interleave$get(MemorySegment seg) {
        return (long)constants$98.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * long long blck_size_interleave;
     * }
     */
    public static void blck_size_interleave$set(MemorySegment seg, long x) {
        constants$98.const$4.set(seg, x);
    }
    public static long blck_size_interleave$get(MemorySegment seg, long index) {
        return (long)constants$98.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void blck_size_interleave$set(MemorySegment seg, long index, long x) {
        constants$98.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle type_size$VH() {
        return constants$98.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long type_size;
     * }
     */
    public static long type_size$get(MemorySegment seg) {
        return (long)constants$98.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long type_size;
     * }
     */
    public static void type_size$set(MemorySegment seg, long x) {
        constants$98.const$5.set(seg, x);
    }
    public static long type_size$get(MemorySegment seg, long index) {
        return (long)constants$98.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void type_size$set(MemorySegment seg, long index, long x) {
        constants$98.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle is_quantized$VH() {
        return constants$99.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool is_quantized;
     * }
     */
    public static boolean is_quantized$get(MemorySegment seg) {
        return (boolean)constants$99.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool is_quantized;
     * }
     */
    public static void is_quantized$set(MemorySegment seg, boolean x) {
        constants$99.const$0.set(seg, x);
    }
    public static boolean is_quantized$get(MemorySegment seg, long index) {
        return (boolean)constants$99.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void is_quantized$set(MemorySegment seg, long index, boolean x) {
        constants$99.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet lang=c :
 * void (*to_float)(void*,float*,long long);
     * }
     */
    public interface to_float {

        void apply(MemorySegment x, MemorySegment y, long k);
        static MemorySegment allocate(to_float fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$99.const$1, fi, constants$31.const$4, scope);
        }
        static to_float ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (MemorySegment _x, MemorySegment _y, long _k) -> {
                try {
                    constants$97.const$5.invokeExact(symbol, _x, _y, _k);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle to_float$VH() {
        return constants$99.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*to_float)(void*,float*,long long);
     * }
     */
    public static MemorySegment to_float$get(MemorySegment seg) {
        return (MemorySegment)constants$99.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*to_float)(void*,float*,long long);
     * }
     */
    public static void to_float$set(MemorySegment seg, MemorySegment x) {
        constants$99.const$2.set(seg, x);
    }
    public static MemorySegment to_float$get(MemorySegment seg, long index) {
        return (MemorySegment)constants$99.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void to_float$set(MemorySegment seg, long index, MemorySegment x) {
        constants$99.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static to_float to_float(MemorySegment segment, Arena scope) {
        return to_float.ofAddress(to_float$get(segment), scope);
    }
    /**
     * {@snippet lang=c :
 * void (*from_float_ref)(float*,void*,long long);
     * }
     */
    public interface from_float_ref {

        void apply(MemorySegment x, MemorySegment y, long k);
        static MemorySegment allocate(from_float_ref fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$99.const$3, fi, constants$31.const$4, scope);
        }
        static from_float_ref ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (MemorySegment _x, MemorySegment _y, long _k) -> {
                try {
                    constants$97.const$5.invokeExact(symbol, _x, _y, _k);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle from_float_ref$VH() {
        return constants$99.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*from_float_ref)(float*,void*,long long);
     * }
     */
    public static MemorySegment from_float_ref$get(MemorySegment seg) {
        return (MemorySegment)constants$99.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*from_float_ref)(float*,void*,long long);
     * }
     */
    public static void from_float_ref$set(MemorySegment seg, MemorySegment x) {
        constants$99.const$4.set(seg, x);
    }
    public static MemorySegment from_float_ref$get(MemorySegment seg, long index) {
        return (MemorySegment)constants$99.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void from_float_ref$set(MemorySegment seg, long index, MemorySegment x) {
        constants$99.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static from_float_ref from_float_ref(MemorySegment segment, Arena scope) {
        return from_float_ref.ofAddress(from_float_ref$get(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


