// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct ggml_backend_feature* (*ggml_backend_get_features_t)(struct ggml_backend_reg* reg);
 * }
 */
public interface ggml_backend_get_features_t {

    MemorySegment apply(MemorySegment reg);
    static MemorySegment allocate(ggml_backend_get_features_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$120.const$2, fi, constants$16.const$0, scope);
    }
    static ggml_backend_get_features_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (MemorySegment _reg) -> {
            try {
                return (MemorySegment)constants$119.const$3.invokeExact(symbol, _reg);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


