// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct llama_model_tensor_buft_override {
 *     char* pattern;
 *     struct ggml_backend_buffer_type* buft;
 * };
 * }
 */
public class llama_model_tensor_buft_override {

    public static MemoryLayout $LAYOUT() {
        return constants$149.const$3;
    }
    public static VarHandle pattern$VH() {
        return constants$149.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * char* pattern;
     * }
     */
    public static MemorySegment pattern$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$149.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * char* pattern;
     * }
     */
    public static void pattern$set(MemorySegment seg, MemorySegment x) {
        constants$149.const$4.set(seg, x);
    }
    public static MemorySegment pattern$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$149.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void pattern$set(MemorySegment seg, long index, MemorySegment x) {
        constants$149.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle buft$VH() {
        return constants$149.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct ggml_backend_buffer_type* buft;
     * }
     */
    public static MemorySegment buft$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$149.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct ggml_backend_buffer_type* buft;
     * }
     */
    public static void buft$set(MemorySegment seg, MemorySegment x) {
        constants$149.const$5.set(seg, x);
    }
    public static MemorySegment buft$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$149.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void buft$set(MemorySegment seg, long index, MemorySegment x) {
        constants$149.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


