// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * _Bool (*llama_set_abort_callback$abort_callback)(void*);
 * }
 */
public interface llama_set_abort_callback$abort_callback {

    boolean apply(MemorySegment data);
    static MemorySegment allocate(llama_set_abort_callback$abort_callback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$181.const$0, fi, constants$35.const$4, scope);
    }
    static llama_set_abort_callback$abort_callback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (MemorySegment _data) -> {
            try {
                return (boolean)constants$36.const$0.invokeExact(symbol, _data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


