// Generated by jextract

package io.gravitee.llama.cpp.macosx.aarch64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct llama_perf_sampler_data {
 *     double t_sample_ms;
 *     int n_sample;
 * };
 * }
 */
public class llama_perf_sampler_data {

    public static MemoryLayout $LAYOUT() {
        return constants$201.const$5;
    }
    public static VarHandle t_sample_ms$VH() {
        return constants$202.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * double t_sample_ms;
     * }
     */
    public static double t_sample_ms$get(MemorySegment seg) {
        return (double)constants$202.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * double t_sample_ms;
     * }
     */
    public static void t_sample_ms$set(MemorySegment seg, double x) {
        constants$202.const$0.set(seg, x);
    }
    public static double t_sample_ms$get(MemorySegment seg, long index) {
        return (double)constants$202.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void t_sample_ms$set(MemorySegment seg, long index, double x) {
        constants$202.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle n_sample$VH() {
        return constants$202.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int n_sample;
     * }
     */
    public static int n_sample$get(MemorySegment seg) {
        return (int)constants$202.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int n_sample;
     * }
     */
    public static void n_sample$set(MemorySegment seg, int x) {
        constants$202.const$1.set(seg, x);
    }
    public static int n_sample$get(MemorySegment seg, long index) {
        return (int)constants$202.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void n_sample$set(MemorySegment seg, long index, int x) {
        constants$202.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


