// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$97 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$97() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buffer"),
        RuntimeHelper.POINTER.withName("base"),
        JAVA_LONG.withName("alignment"),
        JAVA_LONG.withName("offset")
    ).withName("ggml_tallocr");
    static final VarHandle const$1 = constants$97.const$0.varHandle(PathElement.groupElement("buffer"));
    static final VarHandle const$2 = constants$97.const$0.varHandle(PathElement.groupElement("base"));
    static final VarHandle const$3 = constants$97.const$0.varHandle(PathElement.groupElement("alignment"));
    static final VarHandle const$4 = constants$97.const$0.varHandle(PathElement.groupElement("offset"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buffer"),
        RuntimeHelper.POINTER.withName("base"),
        JAVA_LONG.withName("alignment"),
        JAVA_LONG.withName("offset")
    ).withName("ggml_tallocr"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "ggml_tallocr_new",
        constants$97.const$5
    );
}


