// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$74 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$74() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_pool_1d",
        constants$66.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_FLOAT,
        JAVA_FLOAT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_pool_2d",
        constants$74.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_FLOAT,
        JAVA_FLOAT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_pool_2d_back",
        constants$74.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_upscale",
        constants$62.const$5
    );
}


