// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$129 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$129() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_FLOAT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_set_f32_nd",
        constants$129.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_threadpool_new",
        constants$10.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_threadpool_free",
        constants$14.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_threadpool_get_n_threads",
        constants$7.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_threadpool_pause",
        constants$14.const$2
    );
}


