// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$93 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$93() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_quantize_chunk",
        constants$93.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(ggml_to_float_t.class, "apply", constants$14.const$0);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$14.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(ggml_from_float_t.class, "apply", constants$14.const$0);
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("type_name"),
        JAVA_LONG.withName("blck_size"),
        JAVA_LONG.withName("blck_size_interleave"),
        JAVA_LONG.withName("type_size"),
        JAVA_BOOLEAN.withName("is_quantized"),
        MemoryLayout.paddingLayout(7),
        RuntimeHelper.POINTER.withName("to_float"),
        RuntimeHelper.POINTER.withName("from_float_ref")
    ).withName("ggml_type_traits");
}


