// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$181 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$181() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_token_sep",
        constants$7.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_token_nl",
        constants$7.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_token_pad",
        constants$7.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_add_bos_token",
        constants$30.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_add_eos_token",
        constants$30.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_token_fim_pre",
        constants$7.const$1
    );
}


