// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$189 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$189() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_sampler_chain_n",
        constants$7.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_sampler_chain_remove",
        constants$89.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_greedy",
        constants$10.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_dist",
        constants$28.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_softmax",
        constants$10.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_top_k",
        constants$28.const$0
    );
}


