// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;
final class constants$32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$32() {}
    static final VarHandle const$0 = constants$31.const$3.varHandle(PathElement.groupElement("op"));
    static final VarHandle const$1 = constants$31.const$3.varHandle(PathElement.groupElement("flags"));
    static final VarHandle const$2 = constants$31.const$3.varHandle(PathElement.groupElement("view_src"));
    static final VarHandle const$3 = constants$31.const$3.varHandle(PathElement.groupElement("view_offs"));
    static final VarHandle const$4 = constants$31.const$3.varHandle(PathElement.groupElement("data"));
    static final VarHandle const$5 = constants$31.const$3.varHandle(PathElement.groupElement("extra"));
}


