// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$188 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$188() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_sampler_clone",
        constants$10.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_sampler_free",
        constants$14.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_BOOLEAN.withName("no_perf")
        ).withName("llama_sampler_chain_params")
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_sampler_chain_init",
        constants$188.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_sampler_chain_add",
        constants$13.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_sampler_chain_get",
        constants$89.const$2
    );
}


