// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$119 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$119() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_reserve",
        constants$33.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_get_n_backends",
        constants$7.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_get_backend",
        constants$89.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_get_n_splits",
        constants$7.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_get_n_copies",
        constants$7.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_backend_sched_get_buffer_size",
        constants$100.const$3
    );
}


