// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_is_scalar",
        constants$33.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_is_vector",
        constants$33.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_is_matrix",
        constants$33.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_is_3d",
        constants$33.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_n_dims",
        constants$7.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_is_contiguous",
        constants$33.const$0
    );
}


