// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$14 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$14() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "setbuffer",
        constants$14.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "setlinebuf",
        constants$14.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandleVariadic(
        "fprintf",
        constants$9.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandleVariadic(
        "printf",
        constants$7.const$4
    );
}


