// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$94 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$94() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_threadpool_params_init",
        constants$57.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_threadpool_params_match",
        constants$30.const$3
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buffer"),
        RuntimeHelper.POINTER.withName("base"),
        JAVA_LONG.withName("alignment"),
        JAVA_LONG.withName("offset")
    ).withName("ggml_tallocr");
    static final VarHandle const$3 = constants$94.const$2.varHandle(MemoryLayout.PathElement.groupElement("buffer"));
    static final VarHandle const$4 = constants$94.const$2.varHandle(MemoryLayout.PathElement.groupElement("base"));
    static final VarHandle const$5 = constants$94.const$2.varHandle(MemoryLayout.PathElement.groupElement("alignment"));
}


