// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_FLOAT,
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("bits")
        ).withName("")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_bf16_to_fp32",
        constants$27.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_bf16_to_fp32_row",
        constants$11.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_fp32_to_bf16_row_ref",
        constants$11.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_fp32_to_bf16_row",
        constants$11.const$2
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_LONG.withName("mem_size"),
        RuntimeHelper.POINTER.withName("mem_buffer"),
        JAVA_BOOLEAN.withName("no_alloc"),
        MemoryLayout.paddingLayout(7)
    ).withName("ggml_init_params");
}


