// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$167 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$167() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_view_update",
        constants$13.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_get_kv_cache_token_count",
        constants$7.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_get_kv_cache_used_cells",
        constants$7.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_clear",
        constants$14.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_rm",
        constants$167.const$4
    );
}


