// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$165 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$165() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("n_cells"),
        JAVA_INT.withName("n_seq_max"),
        JAVA_INT.withName("token_count"),
        JAVA_INT.withName("used_cells"),
        JAVA_INT.withName("max_contiguous"),
        JAVA_INT.withName("max_contiguous_idx"),
        RuntimeHelper.POINTER.withName("cells"),
        RuntimeHelper.POINTER.withName("cells_sequences")
    ).withName("llama_kv_cache_view");
    static final VarHandle const$1 = constants$165.const$0.varHandle(PathElement.groupElement("n_cells"));
    static final VarHandle const$2 = constants$165.const$0.varHandle(PathElement.groupElement("n_seq_max"));
    static final VarHandle const$3 = constants$165.const$0.varHandle(PathElement.groupElement("token_count"));
    static final VarHandle const$4 = constants$165.const$0.varHandle(PathElement.groupElement("used_cells"));
    static final VarHandle const$5 = constants$165.const$0.varHandle(PathElement.groupElement("max_contiguous"));
}


