// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$89 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$89() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_graph_dump_dot",
        constants$78.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(ggml_log_callback.class, "apply", constants$77.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_log_set",
        constants$10.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_set_zero",
        constants$8.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_quantize_init",
        constants$89.const$4
    );
}


