// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$171 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$171() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_load_session_file",
        constants$170.const$5
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_state_save_file",
        constants$171.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_save_session_file",
        constants$171.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_state_seq_get_size",
        constants$96.const$5
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "llama_state_seq_get_data",
        constants$171.const$5
    );
}


