// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$197 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$197() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_DOUBLE.withName("t_start_ms"),
        JAVA_DOUBLE.withName("t_load_ms"),
        JAVA_DOUBLE.withName("t_p_eval_ms"),
        JAVA_DOUBLE.withName("t_eval_ms"),
        JAVA_INT.withName("n_p_eval"),
        JAVA_INT.withName("n_eval")
    ).withName("llama_perf_context_data"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_perf_context",
        constants$197.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_perf_context_print",
        constants$14.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_perf_context_reset",
        constants$14.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_DOUBLE.withName("t_sample_ms"),
        JAVA_INT.withName("n_sample"),
        MemoryLayout.paddingLayout(4)
    ).withName("llama_perf_sampler_data"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_perf_sampler",
        constants$197.const$4
    );
}


