// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$190 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$190() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_FLOAT,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_top_p",
        constants$190.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_min_p",
        constants$190.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_typical",
        constants$190.const$0
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_FLOAT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_temp",
        constants$190.const$4
    );
}


