// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$175 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$175() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_set_warmup",
        constants$39.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_set_abort_callback",
        constants$78.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_synchronize",
        constants$11.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_get_logits",
        constants$8.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_get_logits_ith",
        constants$86.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_get_embeddings",
        constants$8.const$3
    );
}


