// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$168 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$168() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_cp",
        constants$168.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_keep",
        constants$60.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_add",
        constants$168.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_div",
        constants$168.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_pos_max",
        constants$27.const$2
    );
}


