// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;
final class constants$94 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$94() {}
    static final VarHandle const$0 = constants$93.const$5.varHandle(PathElement.groupElement("type_name"));
    static final VarHandle const$1 = constants$93.const$5.varHandle(PathElement.groupElement("blck_size"));
    static final VarHandle const$2 = constants$93.const$5.varHandle(PathElement.groupElement("blck_size_interleave"));
    static final VarHandle const$3 = constants$93.const$5.varHandle(PathElement.groupElement("type_size"));
    static final VarHandle const$4 = constants$93.const$5.varHandle(PathElement.groupElement("is_quantized"));
    static final VarHandle const$5 = constants$93.const$5.varHandle(PathElement.groupElement("to_float"));
}


