// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$135 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$135() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_cpu_set_abort_callback",
        constants$78.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_cpu_reg",
        constants$8.const$1
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("id"),
        JAVA_FLOAT.withName("logit"),
        JAVA_FLOAT.withName("p")
    ).withName("llama_token_data");
    static final VarHandle const$3 = constants$135.const$2.varHandle(MemoryLayout.PathElement.groupElement("id"));
    static final VarHandle const$4 = constants$135.const$2.varHandle(MemoryLayout.PathElement.groupElement("logit"));
    static final VarHandle const$5 = constants$135.const$2.varHandle(MemoryLayout.PathElement.groupElement("p"));
}


