// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$165 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$165() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_view_free",
        constants$11.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_view_update",
        constants$10.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_kv_self_n_tokens",
        constants$7.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_get_kv_cache_token_count",
        constants$7.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_kv_self_used_cells",
        constants$7.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_get_kv_cache_used_cells",
        constants$7.const$1
    );
}


