// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$112 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$112() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_buffer_type",
        constants$10.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_host_buffer_type",
        constants$10.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_buffer_from_host_ptr",
        constants$63.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_supports_op",
        constants$33.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_supports_buft",
        constants$33.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_backend_dev_offload_op",
        constants$33.const$3
    );
}


