// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$117 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$117() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_init_by_type",
        constants$12.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_init_best",
        constants$10.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_backend_load",
        constants$10.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_unload",
        constants$14.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_backend_load_all",
        constants$33.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_backend_load_all_from_path",
        constants$14.const$2
    );
}


