// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$182 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$182() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_token_fim_suf",
        constants$7.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_token_fim_mid",
        constants$7.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_token_fim_pad",
        constants$7.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_token_fim_rep",
        constants$7.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_token_fim_sep",
        constants$7.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_vocab_cls",
        constants$7.const$4
    );
}


