// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;
final class constants$140 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$140() {}
    static final VarHandle const$0 = constants$139.const$4.varHandle(PathElement.groupElement("token"));
    static final VarHandle const$1 = constants$139.const$4.varHandle(PathElement.groupElement("embd"));
    static final VarHandle const$2 = constants$139.const$4.varHandle(PathElement.groupElement("pos"));
    static final VarHandle const$3 = constants$139.const$4.varHandle(PathElement.groupElement("n_seq_id"));
    static final VarHandle const$4 = constants$139.const$4.varHandle(PathElement.groupElement("seq_id"));
    static final VarHandle const$5 = constants$139.const$4.varHandle(PathElement.groupElement("logits"));
}


