// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$144 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$144() {}
    static final VarHandle const$0 = constants$142.const$2.varHandle(MemoryLayout.PathElement.groupElement("rope_freq_base"));
    static final VarHandle const$1 = constants$142.const$2.varHandle(MemoryLayout.PathElement.groupElement("rope_freq_scale"));
    static final VarHandle const$2 = constants$142.const$2.varHandle(MemoryLayout.PathElement.groupElement("yarn_ext_factor"));
    static final VarHandle const$3 = constants$142.const$2.varHandle(MemoryLayout.PathElement.groupElement("yarn_attn_factor"));
    static final VarHandle const$4 = constants$142.const$2.varHandle(MemoryLayout.PathElement.groupElement("yarn_beta_fast"));
    static final VarHandle const$5 = constants$142.const$2.varHandle(MemoryLayout.PathElement.groupElement("yarn_beta_slow"));
}


