// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$121 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$121() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_tensor_alloc",
        constants$12.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_view_init",
        constants$7.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_backend_cpu_buffer_from_ptr",
        constants$42.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_cpu_buffer_type",
        constants$8.const$1
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_LONG.withName("work_size"),
        RuntimeHelper.POINTER.withName("work_data"),
        JAVA_INT.withName("n_threads"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("threadpool"),
        RuntimeHelper.POINTER.withName("abort_callback"),
        RuntimeHelper.POINTER.withName("abort_callback_data")
    ).withName("ggml_cplan");
    static final VarHandle const$5 = constants$121.const$4.varHandle(MemoryLayout.PathElement.groupElement("work_size"));
}


