// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$115 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$115() {}
    static final VarHandle const$0 = constants$114.const$5.varHandle(PathElement.groupElement("name"));
    static final VarHandle const$1 = constants$114.const$5.varHandle(PathElement.groupElement("value"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(ggml_backend_get_features_t.class, "apply", constants$10.const$5);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_device_register",
        constants$14.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_backend_reg_count",
        constants$34.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "ggml_backend_reg_get",
        constants$115.const$5
    );
}


