// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_step_inplace",
        constants$11.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_tanh",
        constants$11.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_tanh_inplace",
        constants$11.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_elu",
        constants$11.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_elu_inplace",
        constants$11.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_relu",
        constants$11.const$1
    );
}


