// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$168 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$168() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_clear",
        constants$11.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_rm",
        constants$166.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_cp",
        constants$166.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_keep",
        constants$57.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_add",
        constants$166.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_div",
        constants$166.const$3
    );
}


