// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$169 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$169() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_seq_pos_max",
        constants$24.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_defrag",
        constants$11.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_can_shift",
        constants$30.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_kv_cache_update",
        constants$11.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_state_get_size",
        constants$20.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_get_state_size",
        constants$20.const$3
    );
}


