// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$75 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$75() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_upscale_ext",
        constants$66.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_pad",
        constants$66.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_pad_reflect_1d",
        constants$75.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_timestep_embedding",
        constants$75.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_argsort",
        constants$62.const$5
    );
}


