// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$30 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$30() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(ggml_abort_callback.class, "apply", constants$30.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$30.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_guid_matches",
        constants$30.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid();
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "ggml_time_init",
        constants$30.const$5
    );
}


