// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;
final class constants$147 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$147() {}
    static final VarHandle const$0 = constants$144.const$0.varHandle(PathElement.groupElement("cb_eval"));
    static final VarHandle const$1 = constants$144.const$0.varHandle(PathElement.groupElement("cb_eval_user_data"));
    static final VarHandle const$2 = constants$144.const$0.varHandle(PathElement.groupElement("type_k"));
    static final VarHandle const$3 = constants$144.const$0.varHandle(PathElement.groupElement("type_v"));
    static final VarHandle const$4 = constants$144.const$0.varHandle(PathElement.groupElement("logits_all"));
    static final VarHandle const$5 = constants$144.const$0.varHandle(PathElement.groupElement("embeddings"));
}


