// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$40 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$40() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_is_contiguous_0",
        constants$33.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_is_contiguous_1",
        constants$33.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_is_contiguous_2",
        constants$33.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_are_same_shape",
        constants$33.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_are_same_stride",
        constants$33.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_can_repeat",
        constants$33.const$3
    );
}


