// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$170 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$170() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_copy_state_data",
        constants$100.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_state_set_data",
        constants$6.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_set_state_data",
        constants$100.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_state_load_file",
        constants$170.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_load_session_file",
        constants$170.const$3
    );
}


