// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$177 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$177() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_vocab_is_control",
        constants$176.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_vocab_bos",
        constants$7.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_vocab_eos",
        constants$7.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_vocab_eot",
        constants$7.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_vocab_sep",
        constants$7.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_vocab_nl",
        constants$7.const$4
    );
}


