// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fclose",
        constants$7.const$1
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "tmpfile",
        constants$8.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "tmpnam",
        constants$8.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "tmpnam_r",
        constants$8.const$3
    );
}


