// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$96 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$96() {}
    static final VarHandle const$0 = constants$95.const$2.varHandle(PathElement.groupElement("strict_cpu"));
    static final VarHandle const$1 = constants$95.const$2.varHandle(PathElement.groupElement("paused"));
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(512, JAVA_BOOLEAN).withName("cpumask"),
        JAVA_INT.withName("n_threads"),
        JAVA_INT.withName("prio"),
        JAVA_INT.withName("poll"),
        JAVA_BOOLEAN.withName("strict_cpu"),
        JAVA_BOOLEAN.withName("paused"),
        MemoryLayout.paddingLayout(2)
    ).withName("ggml_threadpool_params"),
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_threadpool_params_default",
        constants$96.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_threadpool_params_init",
        constants$60.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_threadpool_params_match",
        constants$33.const$3
    );
}


