// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$138 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$138() {}
    static final VarHandle const$0 = constants$137.const$4.varHandle(PathElement.groupElement("logit"));
    static final VarHandle const$1 = constants$137.const$4.varHandle(PathElement.groupElement("p"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("data"),
        JAVA_LONG.withName("size"),
        JAVA_LONG.withName("selected"),
        JAVA_BOOLEAN.withName("sorted"),
        MemoryLayout.paddingLayout(7)
    ).withName("llama_token_data_array");
    static final VarHandle const$3 = constants$138.const$2.varHandle(PathElement.groupElement("data"));
    static final VarHandle const$4 = constants$138.const$2.varHandle(PathElement.groupElement("size"));
    static final VarHandle const$5 = constants$138.const$2.varHandle(PathElement.groupElement("selected"));
}


