// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$47 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$47() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_get_name",
        constants$10.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_set_name",
        constants$11.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "ggml_format_name",
        constants$11.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_set_input",
        constants$14.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_set_output",
        constants$14.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_set_param",
        constants$13.const$3
    );
}


