// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$51 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$51() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_sqr_inplace",
        constants$11.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_sqrt",
        constants$11.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_sqrt_inplace",
        constants$11.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_log",
        constants$11.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_log_inplace",
        constants$11.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_sin",
        constants$11.const$1
    );
}


