// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$130 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$130() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_cpu_has_avx512_vnni",
        constants$15.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_cpu_has_avx512_bf16",
        constants$15.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_cpu_has_amx_int8",
        constants$15.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_cpu_has_neon",
        constants$15.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_cpu_has_arm_fma",
        constants$15.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_cpu_has_fp16_va",
        constants$15.const$4
    );
}


