// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$124 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$124() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_cpu_buffer_from_ptr",
        constants$45.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_cpu_buffer_type",
        constants$10.const$3
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_LONG.withName("work_size"),
        RuntimeHelper.POINTER.withName("work_data"),
        JAVA_INT.withName("n_threads"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("threadpool"),
        RuntimeHelper.POINTER.withName("abort_callback"),
        RuntimeHelper.POINTER.withName("abort_callback_data")
    ).withName("ggml_cplan");
    static final VarHandle const$3 = constants$124.const$2.varHandle(PathElement.groupElement("work_size"));
    static final VarHandle const$4 = constants$124.const$2.varHandle(PathElement.groupElement("work_data"));
    static final VarHandle const$5 = constants$124.const$2.varHandle(PathElement.groupElement("n_threads"));
}


