// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$79 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$79() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(ggml_custom3_op_f32_t.class, "apply", constants$78.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$78.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_map_unary_f32",
        constants$9.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_map_unary_inplace_f32",
        constants$9.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_map_binary_f32",
        constants$58.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_map_binary_inplace_f32",
        constants$58.const$0
    );
}


