// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$32() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_print_object",
        constants$11.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_print_objects",
        constants$11.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_nelements",
        constants$20.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_nrows",
        constants$20.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_nbytes",
        constants$20.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_nbytes_pad",
        constants$20.const$3
    );
}


