// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$111 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$111() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_reg_get_proc_address",
        constants$9.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(ggml_backend_split_buffer_type_t.class, "apply", constants$10.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$10.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(ggml_backend_set_n_threads_t.class, "apply", constants$57.const$5);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$57.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(ggml_backend_dev_get_extra_bufts_t.class, "apply", constants$8.const$3);
}


