// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$191 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$191() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_FLOAT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_temp_ext",
        constants$191.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_xtc",
        constants$191.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_top_n_sigma",
        constants$190.const$4
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "llama_sampler_init_mirostat",
        constants$191.const$5
    );
}


