// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$18 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$18() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vscanf",
        constants$9.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vsscanf",
        constants$15.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "fgetc",
        constants$7.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getc",
        constants$7.const$4
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getchar",
        constants$18.const$4
    );
}


