// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$104 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$104() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ggml_backend_name",
        constants$10.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ggml_backend_free",
        constants$14.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ggml_backend_get_default_buffer_type",
        constants$10.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_backend_alloc_buffer",
        constants$45.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ggml_backend_get_alignment",
        constants$23.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_backend_get_max_size",
        constants$23.const$3
    );
}


