// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$125 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$125() {}
    static final VarHandle const$0 = constants$124.const$2.varHandle(PathElement.groupElement("threadpool"));
    static final VarHandle const$1 = constants$124.const$2.varHandle(PathElement.groupElement("abort_callback"));
    static final VarHandle const$2 = constants$124.const$2.varHandle(PathElement.groupElement("abort_callback_data"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ggml_numa_init",
        constants$92.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_BOOLEAN);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ggml_is_numa",
        constants$125.const$4
    );
}


