// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final VarHandle const$0 = constants$1.const$5.varHandle(MemoryLayout.PathElement.groupElement("_freeres_buf"));
    static final VarHandle const$1 = constants$1.const$5.varHandle(MemoryLayout.PathElement.groupElement("__pad5"));
    static final VarHandle const$2 = constants$1.const$5.varHandle(MemoryLayout.PathElement.groupElement("_mode"));
    static final VarHandle const$3 = RuntimeHelper.POINTER.varHandle();
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("stdin", RuntimeHelper.POINTER);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("stdout", RuntimeHelper.POINTER);
}


