// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;

final class constants$159 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$159() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llama_model_rope_type",
        constants$7.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llama_model_n_ctx_train",
        constants$7.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llama_model_n_embd",
        constants$7.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llama_model_n_layer",
        constants$7.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llama_model_n_head",
        constants$7.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llama_model_n_head_kv",
        constants$7.const$4
    );
}


