// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$150 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$150() {}
    static final VarHandle const$0 = constants$148.const$5.varHandle(PathElement.groupElement("only_copy"));
    static final VarHandle const$1 = constants$148.const$5.varHandle(PathElement.groupElement("pure"));
    static final VarHandle const$2 = constants$148.const$5.varHandle(PathElement.groupElement("keep_split"));
    static final VarHandle const$3 = constants$148.const$5.varHandle(PathElement.groupElement("imatrix"));
    static final VarHandle const$4 = constants$148.const$5.varHandle(PathElement.groupElement("kv_overrides"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("token"),
        JAVA_FLOAT.withName("bias")
    ).withName("llama_logit_bias");
}


