// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.foreign.*;

/**
 * {@snippet :
 * long (*cookie_read_function_t)(void* __cookie,char* __buf,unsigned long __nbytes);
 * }
 */
public interface cookie_read_function_t {

    long apply(MemorySegment __cookie, MemorySegment __buf, long __nbytes);
    static MemorySegment allocate(cookie_read_function_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$6.const$4, fi, constants$6.const$3, scope);
    }
    static cookie_read_function_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (MemorySegment ___cookie, MemorySegment ___buf, long ___nbytes) -> {
            try {
                return (long)constants$6.const$5.invokeExact(symbol, ___cookie, ___buf, ___nbytes);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


