// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import io.gravitee.llama.cpp.linux.x86_64._IO_FILE;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _IO_FILE FILE;
 * }
 */
public final class FILE extends _IO_FILE {

    // Suppresses default constructor, ensuring non-instantiability.
    private FILE() {}
}


