// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import io.gravitee.llama.cpp.linux.x86_64._G_fpos_t;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _G_fpos_t fpos_t;
 * }
 */
public final class fpos_t extends _G_fpos_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private fpos_t() {}
}


