// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.foreign.*;

/**
 * {@snippet :
 * struct ggml_backend_buffer_type* (*ggml_backend_split_buffer_type_t)(int main_device,float* tensor_split);
 * }
 */
public interface ggml_backend_split_buffer_type_t {

    MemorySegment apply(int main_device, MemorySegment tensor_split);
    static MemorySegment allocate(ggml_backend_split_buffer_type_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$113.const$4, fi, constants$12.const$2, scope);
    }
    static ggml_backend_split_buffer_type_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int _main_device, MemorySegment _tensor_split) -> {
            try {
                return (MemorySegment)constants$113.const$5.invokeExact(symbol, _main_device, _tensor_split);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


