// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.foreign.*;

/**
 * {@snippet :
 * void (*ggml_binary_op_f32_t)(int,float*,float*,float*);
 * }
 */
public interface ggml_binary_op_f32_t {

    void apply(int _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3);
    static MemorySegment allocate(ggml_binary_op_f32_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$80.const$3, fi, constants$80.const$2, scope);
    }
    static ggml_binary_op_f32_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int __x0, MemorySegment __x1, MemorySegment __x2, MemorySegment __x3) -> {
            try {
                constants$80.const$4.invokeExact(symbol, __x0, __x1, __x2, __x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


