// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.foreign.*;

/**
 * {@snippet :
 * _Bool (*ggml_abort_callback)(void* data);
 * }
 */
public interface ggml_abort_callback {

    boolean apply(MemorySegment data);
    static MemorySegment allocate(ggml_abort_callback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$33.const$1, fi, constants$33.const$0, scope);
    }
    static ggml_abort_callback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (MemorySegment _data) -> {
            try {
                return (boolean)constants$33.const$2.invokeExact(symbol, _data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


