// Generated by jextract

package io.gravitee.llama.cpp.linux.x86_64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct llama_kv_cache_view_cell {
 *     llama_pos pos;
 * };
 * }
 */
public class llama_kv_cache_view_cell {

    public static MemoryLayout $LAYOUT() {
        return constants$163.const$0;
    }
    public static VarHandle pos$VH() {
        return constants$163.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * llama_pos pos;
     * }
     */
    public static int pos$get(MemorySegment seg) {
        return (int)constants$163.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * llama_pos pos;
     * }
     */
    public static void pos$set(MemorySegment seg, int x) {
        constants$163.const$1.set(seg, x);
    }
    public static int pos$get(MemorySegment seg, long index) {
        return (int)constants$163.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void pos$set(MemorySegment seg, long index, int x) {
        constants$163.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


